version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    image: phpoidc/fpm:latest
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/phpOp
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

  #MySQL Service
  mysql:
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: phpoidc
      MYSQL_USER: phpoidc
      MYSQL_PASSWORD: phpoidc
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - app-network
  # MailDev 
  maildev:
    image: maildev/maildev
    container_name: maildev
    restart: unless-stopped
    tty: true
    ports:
      - "1080:80"
    environment:
      MYSQL_DATABASE: phpoidc
      MYSQL_USER: phpoidc
      MYSQL_PASSWORD: phpoidc
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge