name: Build and push Docker images
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build phpOp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Docker repository to tag the image with
          repository: phpoidc/phpoidc
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: phpop
          # Automatically tags the built image with the git reference as per the readme
          path: .
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: Dockerfile.phpOp
          add_git_labels: yes
          # Whether to push the image
          push: true